services:
  backend:
    image: riot3a/yolo-backend:v1.0.0
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yolo
    networks:
      - app-network
    depends_on:
      - mongodb

  client:
    image: riot3a/yolo-client:v1.0.0
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
